languageCode = "de-DE"
title = "Turmhof Wehrle Hohentengen a.H. - Ferienwohnung in Hohentengen am Hochrhein"

[params]
	# To provide some metadata for search engines feel free to add a few
        # information about you and your website.
	name = "Turmhof Wehrle"
	description = "Turmhof Wehrle Hohentengen a.H. - Ferienwohnung in Hohentengen am Hochrhein"

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = ""	# **Ferien auf dem Turmhof.<br>Ruhe und Entspannung <br>im Herzen der Natur.**
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		dribbble = ""
		facebook = ""

		copyright = [
			"&copy; Turmhof Wehrle",
			"<a href='http://www.hohentengen.de/' target='_blank' title='external link to'>Hohentengen a.H.</a>"
		]


	[params.about]
		title = "Herzlich Willkommen auf dem Turmhof"
		content = "Genießen Sie Natur, Ruhe und Erholung in unserer geräumigen, gemütlich eingerichteten Dachgeschoß-Ferienwohnung. Der Südbalkon bietet einen wunderschönen Ausblick über das Rheintal bis hinüber in die Schweiz. Der Turmhof gehört zum Ortsteil Lienheim der Gemeinde Hohentengen am Hochrhein, und liegt einige Kilometer außerhalb des Ortskerns."


	[params.portfolio]
		title = "Die Ferienwohnung"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/IMG_2852.jpg"
			thumb = "thumbs/IMG_2852.jpg"
			title = "Schlafzimmer Nord"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2851.jpg"
			thumb = "thumbs/IMG_2851.jpg"
			title = "Schlafzimmer Nord"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2915.jpg"
			thumb = "thumbs/IMG_2915.jpg"
			title = "Schlafzimmer Süd"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2923.jpg"
			thumb = "thumbs/IMG_2923.jpg"
			title = "Ausblick Schlafzimmer Süd"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2879.jpg"
			thumb = "thumbs/IMG_2879.jpg"
			title = "Südbalkon"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2901.jpg"
			thumb = "thumbs/IMG_2901.jpg"
			title = "Wohn- und Esszimmer"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2904.jpg"
			thumb = "thumbs/IMG_2904.jpg"
			title = "Wohn- und Esszimmer"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2909.jpg"
			thumb = "thumbs/IMG_2909.jpg"
			title = "Wohn- und Esszimmer"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2911.jpg"
			thumb = "thumbs/IMG_2911.jpg"
			title = "Wohn- und Esszimmer"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2928.jpg"
			thumb = "thumbs/IMG_2928.jpg"
			title = "Flur"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2931.jpg"
			thumb = "thumbs/IMG_2931.jpg"
			title = "Badezimmer"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2932.jpg"
			thumb = "thumbs/IMG_2932.jpg"
			title = "Badezimmer"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/k17.jpg"
			thumb = "thumbs/k17.jpg"
			title = "Küche"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/k18.jpg"
			thumb = "thumbs/k18.jpg"
			title = "Küche"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/k20.jpg"
			thumb = "thumbs/k20.jpg"
			title = "Küche"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/IMG_2933.jpg"
			thumb = "thumbs/IMG_2933.jpg"
			title = "Hauseingang"
			description = ""


	[params.contact]

		address = [
            "Joachim Wehrle",
            "Ferienwohnung",
            "Turmhof",
            "79801 Hohentengen a.H.",
            "Deutschland",
		]
		phone = "+49-7742-1314"

		email = "turmhof.wehrle@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Buchungsanfrage"
			submit = "Abschicken"